import type { StorySlide } from './story-slide'

export interface PortfolioProject {
  id: string
  slug: string
  title: string
  tagline: string
  description: string
  role: string
  duration: string
  year: string
  category: 'ai' | 'web' | 'mobile' | 'data' | 'other'
  tech: string[]
  highlights: string[]
  metrics?: {
    label: string
    value: string
  }[]
  /** Optional override for the project metrics section heading copy. */
  metricsSection?: {
    eyebrow: string
    headline: string
  }
  images: {
    thumbnail: string
    /** Preferred image for work listing cards and hero previews */
    cover?: string
    /** Work listing cover when case study should stay image-free */
    workCover?: string
    /** Optional looping hero video (case study header). Poster falls back to cover. */
    coverVideo?: string
    /** CSS aspect-ratio for cover image, e.g. "1024/490" */
    coverAspect?: string
    /** Screenshot frame background. Dark UI products use a black frame instead of white. */
    screenshotFrame?: 'light' | 'dark'
    /** Default frame style for this project's screenshots. */
    screenshotStyle?: 'minimal' | 'device'
    gallery?: string[]
  }
  links: {
    live?: string
    github?: string
    case_study?: string
    /** Custom CTA label when linking to live (e.g. "Live Page") */
    ctaLabel?: string
  }
  color: string
  featured?: boolean
  slides?: StorySlide[]
}

export const portfolioProjects: PortfolioProject[] = [
  {
    id: '7',
    slug: 'digipropass',
    title: 'DigiProPass',
    tagline: 'Digital Product Passport Platform for Sustainable Products',
    description: 'A web-based platform designed to help brands comply with upcoming European regulations that mandate Digital Product Passports (DPP) for consumer products. The platform bridges the gap between regulatory compliance, brand transparency, and consumer trust.',
    role: 'Full Stack Developer',
    duration: '6 months',
    year: '2024',
    category: 'web',
    tech: ['Django', 'Django REST Framework', 'PostgreSQL', 'AWS', 'Docker', 'JWT', 'OAuth'],
    highlights: [
      'Alignment with upcoming EU compliance requirements',
      'Product-level transparency, not just brand-level claims',
      'Scalable QR-based digital passport generation',
      'Clean separation of admin, business, and consumer layers',
      'Sustainability scoring baked directly into product workflows',
    ],
    metrics: [
      { label: 'Products Tracked', value: '10K+' },
      { label: 'Compliance Rate', value: '100%' },
      { label: 'Brand Partners', value: '50+' },
    ],
    images: {
      thumbnail: '/dpplogo.svg',
      cover: '/dpp-dashboard.png',
      coverVideo: '/Digi1.mp4',
      coverAspect: '1024/490',
      screenshotStyle: 'device',
    },
    links: {
      live: 'https://digipropass.com/',
    },
    color: '#6366F1',
    featured: true,
    slides: [
      {
        id: 1,
        type: 'intro',
        title: 'Project Overview',
        content: 'DigiProPass is a web-based platform designed to help brands comply with upcoming European regulations that mandate Digital Product Passports (DPP) for consumer products. End consumers can scan a QR code and instantly view sustainability details, origin, materials, and environmental impact scores.',
        highlight: 'The platform bridges the gap between regulatory compliance, brand transparency, and consumer trust.',
      },
      {
        id: 2,
        type: 'scene',
        title: 'How It Started',
        content: 'The DigiProPass team approached us after finding our work on LinkedIn. After a discovery call, the idea became a working platform with a clear technical and business roadmap.',
        highlight: 'From LinkedIn connection to fully functional platform.',
      },
      {
        id: 3,
        type: 'problem',
        title: 'The Problem',
        content: 'The European Union is moving toward mandatory Digital Product Passports for products sold within its region. Most brands are not technically equipped to track sustainability data at a product level, maintain ingredient and origin transparency, or generate and manage QR-based digital passports at scale.',
        highlight: 'DigiProPass solves this by providing a centralized system to create, manage, and distribute digital product passports.',
        backgroundVideo: '/Digi2.mp4',
      },
      {
        id: 4,
        type: 'stats',
        title: 'Target Users',
        content: 'The platform serves both B2B and B2C users with different access levels and capabilities.',
        stats: [
          { value: 'B2B', label: 'Consumer Goods Brands', icon: '🏢' },
          { value: 'B2B', label: 'Manufacturers', icon: '🏭' },
          { value: 'B2B', label: 'Exporters', icon: '🚢' },
          { value: 'B2C', label: 'End Consumers', icon: '👥' },
        ],
        highlight: 'Secondary users include compliance teams, product managers, and sustainability officers.',
      },
      {
        id: 5,
        type: 'architecture',
        title: 'Platform Architecture',
        content: 'The platform was designed with three clear layers for complete separation of concerns.',
        layers: [
          { name: 'Super Admin Panel', description: 'Used internally by DigiProPass for platform management', icon: '🔐', color: '#8B5CF6' },
          { name: 'Business Dashboard', description: 'Used by brands and manufacturers to manage products', icon: '📊', color: '#3B82F6' },
          { name: 'Public Passport View', description: 'Used by end consumers after scanning QR codes', icon: '📱', color: '#10B981' },
        ],
        highlight: 'Three-tier architecture ensures scalability and security.',
        backgroundVideo: '/Digi3.mp4',
      },
      {
        id: 16,
        type: 'scene',
        title: 'Sign-In Experience',
        content: 'A split-screen sign-in pairs a focused email-and-password form with DigiProPass branding and a clear path for new brands to contact sales, professional from the first interaction.',
        highlight: 'Brand and product identity aligned from the first screen.',
        image: '/dpp-login.png',
      },
      {
        id: 6,
        type: 'scene',
        title: 'Business Dashboard',
        content: 'The core product-facing interface where brands manage their digital passports. Features include self-service onboarding, CSV bulk import, product editing with sustainability data, and multi-passport linking per product.',
        highlight: 'Real-time metrics including CO₂ emissions, water usage, and eco scores.',
        image: '/dpp-dashboard.png',
      },
      {
        id: 7,
        type: 'process',
        title: 'Role-Based Access Control',
        content: 'Supporting organizations of different sizes with flexible permission systems.',
        steps: [
          { number: 1, title: 'Admin Role', description: 'Full access to all features including product creation, passport generation, and data editing' },
          { number: 2, title: 'Manager Role', description: 'Limited access for day-to-day operations and ingredient management' },
          { number: 3, title: 'Custom Roles', description: 'Future extensibility for specialized permissions per organization needs' },
        ],
      },
      {
        id: 8,
        type: 'scene',
        title: 'Product Management',
        content: 'Brands can add products individually or bulk upload via CSV. Each product can be categorized, tagged, and enriched with detailed sustainability data including materials, ingredients, and country of origin.',
        highlight: 'Bulk upload and category-based filtering for efficient product management.',
        image: '/dpp-products.png',
      },
      {
        id: 9,
        type: 'process',
        title: 'Sustainability Scoring Engine',
        content: 'One of the most critical features - calculating environmental impact scores.',
        steps: [
          { number: 1, title: 'Input Ingredients', description: 'Brands input all ingredients and materials used in their products' },
          { number: 2, title: 'Define Percentages', description: 'Specify the percentage contribution of each ingredient' },
          { number: 3, title: 'Algorithm Processing', description: 'Proprietary algorithm processes the ingredient data' },
          { number: 4, title: 'Score Generation', description: 'Calculate overall sustainability score for the product' },
        ],
      },
      {
        id: 10,
        type: 'scene',
        title: 'My Brand',
        content: 'Brands manage their identity from a dedicated profile hub: logo, location, subscription tier, product and user counts, and tabbed access to overview, users, products, and brand settings.',
        highlight: 'Subscription status, location, and brand metrics in one place.',
        image: '/dpp-my-brand.png',
      },
      {
        id: 11,
        type: 'scene',
        title: 'News Feed',
        content: 'A curated sustainability news feed keeps brand teams informed on traceability, digital passports, and industry trends, with search, featured posts, and sidebar highlights for premium content.',
        highlight: 'Industry insights and compliance updates without leaving the platform.',
        image: '/dpp-news-feed.png',
      },
      {
        id: 12,
        type: 'stats',
        title: 'Technology & Status',
        content: 'Core platform fully designed and developed with MVP-level implementation complete.',
        stats: [
          { value: '100%', label: 'Core Features', icon: '✅' },
          { value: 'MVP', label: 'Implementation', icon: '🚀' },
          { value: 'Ready', label: 'Pilot Onboarding', icon: '🎯' },
          { value: 'Planned', label: 'E-commerce Integrations', icon: '🔮' },
        ],
        highlight: 'Future scope includes Shopify, WooCommerce, deeper analytics, and regulatory exports.',
      },
      {
        id: 13,
        type: 'conclusion',
        title: 'Key Differentiators',
        content: 'DigiProPass stands out with alignment to upcoming EU compliance requirements, product-level transparency (not just brand-level claims), scalable QR-based passport generation, clean separation of admin/business/consumer layers, and sustainability scoring built into workflows.',
        highlight: 'MVP complete. Ready for pilot brand onboarding.',
        backgroundVideo: '/Digi4.mp4',
      },
      {
        id: 15,
        type: 'gallery',
        title: 'Project Gallery',
        content: 'Explore the DigiProPass platform through sign-in, dashboard metrics, product management, brand profiles, and the sustainability news feed.',
        galleryImages: [
          '/dpp-login.png',
          '/dpp-dashboard.png',
          '/dpp-products.png',
          '/dpp-my-brand.png',
          '/dpp-news-feed.png',
        ],
      },
    ],
  },
  {
    id: '8',
    slug: 'healthy-fasal',
    title: 'Healthy Fasal',
    tagline: 'Zero-Inventory Farm-to-Vendor Grocery Supply Platform',
    description: 'A scalable, zero-inventory grocery procurement and distribution platform designed to simplify the farm-to-vendor supply chain while ensuring freshness, reducing wastage, and improving margins for all stakeholders.',
    role: 'Full Stack Developer',
    duration: '4 months',
    year: '2025',
    category: 'web',
    tech: ['React', 'Node.js', 'PostgreSQL', 'Express', 'AWS', 'Docker'],
    highlights: [
      'Zero-inventory model - procurement only after confirmed demand',
      'Multi-panel architecture for scalable operations',
      'Wallet-based ordering system for vendors',
      'Real-time order tracking and fulfillment',
      'Generating ₹1 Crore+ monthly turnover',
    ],
    metrics: [
      { label: 'Monthly Revenue', value: '₹1Cr+' },
      { label: 'Collection Centers', value: 'Multi' },
      { label: 'Order Volume', value: 'High' },
    ],
    images: {
      thumbnail: '/hf-logo.png',
      cover: '/hf-work-cover.png',
      coverVideo: '/farm5.mp4',
      coverAspect: '1024/490',
      screenshotStyle: 'device',
    },
    links: {
      live: 'https://healthyfasal.com/',
    },
    color: '#22C55E',
    featured: true,
    slides: [
      {
        id: 1,
        type: 'intro',
        title: 'Project Overview',
        content: 'Healthy Fasal is a scalable, zero-inventory grocery procurement and distribution platform designed to simplify the farm-to-vendor supply chain while ensuring freshness, reducing wastage, and improving margins for all stakeholders.',
        highlight: 'Procure fresh produce only when demand exists and deliver it efficiently to vendors without holding inventory.',
      },
      {
        id: 2,
        type: 'scene',
        title: 'How It Started',
        content: 'The project came through a trusted network. Healthy Fasal is led by a farmer and logistics operator who saw deep inefficiencies in the traditional grocery supply chain.',
        highlight: 'Farming and logistics in one operation: the right team for this problem.',
      },
      {
        id: 3,
        type: 'problem',
        title: 'The Problem',
        content: 'Groceries often reach vendors late and stale due to inventory mismanagement. Middle layers cause delays, wastage, and poor quality control. Vendors lack a structured ordering system, and farmers are disconnected from real demand signals.',
        highlight: 'Traditional supply chains are broken - fresh produce becomes stale before reaching vendors.',
        backgroundVideo: '/farm4.mp4',
      },
      {
        id: 4,
        type: 'solution',
        title: 'The Zero-Inventory Philosophy',
        content: 'Healthy Fasal was designed around one strong principle: Zero Inventory. Demand first. Procurement second. Instead of stocking groceries, orders are collected from vendors, procurement happens only after confirmed demand, farmers supply fresh produce, and collection centers handle aggregation and dispatch.',
        highlight: 'No pre-stocking. No wastage. Fresh produce every time.',
      },
      {
        id: 5,
        type: 'architecture',
        title: 'Multi-Panel Architecture',
        content: 'The system was architected from day one for scalability, with four distinct operational fronts.',
        layers: [
          { name: 'Super Admin Panel', description: 'Central command center for multi-city operations', icon: '🏢', color: '#22C55E' },
          { name: 'Collection Center Panel', description: 'Operational backbone for procurement and dispatch', icon: '📦', color: '#16A34A' },
          { name: 'Vendor Panel', description: 'Ordering interface for grocery shop owners', icon: '🛒', color: '#15803D' },
          { name: 'Sales Panel', description: 'On-ground team for vendor onboarding', icon: '👥', color: '#166534' },
        ],
        highlight: 'Four panels working in sync for seamless operations.',
      },
      {
        id: 6,
        type: 'features',
        title: 'Super Admin Capabilities',
        content: 'The Super Admin Panel acts as the central command center for Healthy Fasal.',
        features: [
          { icon: '🏙️', title: 'Multi-City Control', description: 'Create and manage multiple collection centers across cities' },
          { icon: '📍', title: 'Area Management', description: 'Area-wise operational control and routing' },
          { icon: '✅', title: 'Vendor Approval', description: 'Approve and manage vendors/shopkeepers' },
          { icon: '📊', title: 'Order Oversight', description: 'Monitor orders, payments, and delivery status' },
          { icon: '⚙️', title: 'Platform Config', description: 'Control platform-wide configurations' },
          { icon: '🚀', title: 'Scalability', description: 'Expand city-by-city without architectural changes' },
        ],
      },
      {
        id: 17,
        type: 'scene',
        title: 'Sign-In Experience',
        content: 'A welcoming split-screen login pairs farm photography with a focused sign-in flow, setting the tone for a platform built around fresh produce and operational clarity from the first interaction.',
        highlight: 'Brand and product identity aligned from the first screen.',
        image: '/hf-login.png',
      },
      {
        id: 7,
        type: 'scene',
        title: 'Trade Inquiries',
        content: 'Sales teams capture leads from on-ground shop visits with status tracking, city filters, and assignment workflows. Admins review pending, approved, and rejected inquiries with full shop and contact details in a card-based grid.',
        highlight: 'On-ground sales execution with structured lead capture and approval.',
        image: '/hf-trade-inquiries.png',
      },
      {
        id: 8,
        type: 'scene',
        title: 'Vendor Ordering Experience',
        content: 'Vendors get a clean, intuitive interface to browse available products, view prices in Hindi and Marathi, and add items to cart. The wallet-based system shows their balance and allows quick checkout without payment friction.',
        highlight: 'Wallet credits eliminate payment delays and simplify operations.',
        image: '/hf-vendor.png',
      },
      {
        id: 9,
        type: 'process',
        title: 'End-to-End Order Flow',
        content: 'The complete journey from vendor order to delivery - all without any inventory storage.',
        steps: [
          { number: 1, title: 'Vendor Places Order', description: 'Vendor orders using wallet balance through the app' },
          { number: 2, title: 'Routed to Center', description: 'Order automatically routed to assigned collection center' },
          { number: 3, title: 'Farmer Procurement', description: 'Collection center procures fresh produce from farmers' },
          { number: 4, title: 'Pack & Dispatch', description: 'Packing lists, challans, and invoices generated' },
          { number: 5, title: 'Delivery Complete', description: 'Order delivered and marked complete in system' },
        ],
      },
      {
        id: 10,
        type: 'scene',
        title: 'Order Management',
        content: 'Real-time order tracking with status filters, payment tracking, and multi-center support. Admins can see dispatched and delivered orders at a glance with detailed line items and one-click access to order details.',
        highlight: 'Complete visibility from order placement to delivery.',
        image: '/hf-orders.png',
      },
      {
        id: 16,
        type: 'scene',
        title: 'Wallet Management',
        content: 'Shop wallets power the zero-inventory ordering flow. Admins view total balances, locked amounts, and available credits across collection centers, with search, filtering, and top-up workflows for every vendor account.',
        highlight: 'Centralized wallet control keeps vendor checkout fast and reliable.',
        image: '/hf-wallet.png',
      },
      {
        id: 11,
        type: 'process',
        title: 'Sales Team Workflow',
        content: 'Built specifically for on-ground execution, which is critical in grocery distribution.',
        steps: [
          { number: 1, title: 'Visit Shops', description: 'Sales team physically visits local grocery shops' },
          { number: 2, title: 'Educate & Collect', description: 'Explain Healthy Fasal benefits, collect leads and feedback' },
          { number: 3, title: 'Submit Lead', description: 'Add interested vendors to the platform' },
          { number: 4, title: 'Admin Approval', description: 'Super Admin validates and approves the vendor' },
          { number: 5, title: 'Vendor Onboarded', description: 'Login credentials sent, vendor starts ordering digitally' },
        ],
      },
      {
        id: 12,
        type: 'stats',
        title: 'Zero-Inventory Benefits',
        content: 'The core moat of Healthy Fasal - demand-driven supply chain.',
        stats: [
          { value: '~0%', label: 'Wastage', icon: '🗑️' },
          { value: '100%', label: 'Fresh Produce', icon: '🥬' },
          { value: '0', label: 'Capital Lock-in', icon: '💰' },
          { value: '✓', label: 'Farmer Alignment', icon: '🤝' },
        ],
        highlight: 'No pre-stocking means better freshness, reduced waste, and aligned incentives.',
      },
      {
        id: 13,
        type: 'stats',
        title: 'Impact & Traction',
        content: 'This is not a concept  it\'s a working revenue-generating system.',
        stats: [
          { value: '₹1Cr+', label: 'Monthly Turnover', icon: '📈' },
          { value: 'Live', label: 'In Production', icon: '🟢' },
          { value: 'Multi', label: 'Collection Centers', icon: '🏭' },
          { value: '1000+', label: 'Orders Processed', icon: '📦' },
        ],
        highlight: 'Real-world validation of zero-inventory model with proven revenue.',
      },
      {
        id: 14,
        type: 'conclusion',
        title: 'Why This Project Stands Out',
        content: 'Healthy Fasal solves a real, ground-level problem with the founder\'s deep domain expertise. The strong operational logic combined with the zero-inventory model reduces risk while the proven traction and revenue validate the business model.',
        highlight: 'From farm to vendor, fresh produce with zero waste.',
        backgroundVideo: '/farm6.mp4',
      },
      {
        id: 15,
        type: 'gallery',
        title: 'Platform Gallery',
        content: 'Explore the Healthy Fasal platform through vendor ordering, order management, wallet controls, trade inquiries, and the sign-in experience.',
        galleryImages: [
          '/hf-login.png',
          '/hf-vendor.png',
          '/hf-orders.png',
          '/hf-wallet.png',
          '/hf-trade-inquiries.png',
        ],
      },
    ],
  },
  {
    id: '9',
    slug: 'natvoiz-ai',
    title: 'Natvoiz AI Voice Bot',
    tagline: 'Enterprise-Grade, Configurable, Low-Latency AI Voice Automation',
    description: 'An end-to-end AI Voice Bot Platform capable of handling enterprise-scale voice interactions across recruitment, insurance, sales, and customer support use cases. Built for Natsoft, a US-based enterprise with 2,000+ employees.',
    role: 'AI Engineer & Full Stack Developer',
    duration: '8 months',
    year: '2023',
    category: 'ai',
    tech: ['Python', 'FastAPI', 'OpenAI', 'Deepgram', 'ElevenLabs', 'WebSockets', 'React', 'PostgreSQL'],
    highlights: [
      'Reduced latency from ~2s to ~300ms for human-like conversations',
      'Configurable STT, LLM, and TTS providers per flow',
      'Visual drag-and-drop voice flow builder',
      'RAG support with knowledge base integration',
      '35-45% reduction in manual follow-ups at Natsoft',
    ],
    metrics: [
      { label: 'Latency', value: '~300ms' },
      { label: 'Call Logs', value: '500+' },
      { label: 'Voice Flows', value: '8+' },
    ],
    images: {
      thumbnail: '/nv-logo.svg',
      coverAspect: '1024/490',
      screenshotFrame: 'dark',
      screenshotStyle: 'device',
    },
    links: {
      live: 'https://natsoft.com/',
    },
    color: '#7C3AED',
    featured: true,
    slides: [
      {
        id: 1,
        type: 'intro',
        title: 'Project Overview',
        content: 'Natvoiz is an end-to-end AI Voice Bot Platform capable of handling enterprise-scale voice interactions across recruitment, insurance, sales, and customer support use cases. Built for Natsoft, a US-based consulting enterprise with over 2,000 employees.',
        highlight: 'Replace repetitive, high-volume human calling workflows with AI-driven, human-like voice conversations.',
      },
      {
        id: 2,
        type: 'scene',
        title: 'The Client: Natsoft',
        content: 'Natsoft is a US-based consulting enterprise with over 2,000 employees and BPO operations. They faced major operational issues in their recruitment workflow - high recruiter workload, candidate drop-offs, and no structured way to capture feedback.',
        highlight: 'From recruitment automation to a full enterprise voice platform.',
      },
      {
        id: 3,
        type: 'problem',
        title: 'The Problem',
        content: 'High recruiter workload due to repetitive follow-ups. High candidate drop-off after offer rollout. No structured way to capture why candidates reject offers. Manual follow-ups leading to delays, inconsistent data, and recruiter burnout.',
        highlight: 'They needed an AI system that could screen candidates, follow up automatically, and share structured insights back to their CRM.',
      },
      {
        id: 4,
        type: 'solution',
        title: 'Platform Vision',
        content: 'Instead of building a single-purpose bot, we proposed and built a platform  a configurable AI voice orchestration system that non-technical users can adapt to multiple business workflows without engineering support.',
        highlight: 'This decision later enabled rapid expansion into insurance, sales, and customer support use cases.',
      },
      {
        id: 5,
        type: 'scene',
        title: 'Visual Flow Builder',
        content: 'A user-friendly drag-and-drop flow builder where users can create conversation nodes, define prompts and responses, connect logic paths visually, configure fallback scenarios, and design complex multi-step call flows.',
        highlight: 'Usable by HR, Ops, and Business teams  not just engineers.',
      },
      {
        id: 6,
        type: 'features',
        title: 'AI & Voice Stack',
        content: 'Fully configurable speech-to-text, LLM, and text-to-speech providers for each flow.',
        features: [
          { icon: '🎤', title: 'Speech-to-Text', description: 'Deepgram, Google STT, AssemblyAI, Gladia' },
          { icon: '🧠', title: 'LLM Providers', description: 'OpenAI GPT models, Google LLMs for reasoning' },
          { icon: '🔊', title: 'Text-to-Speech', description: 'ElevenLabs, Google TTS with configurable voice/tone' },
          { icon: '💬', title: 'Intent Detection', description: 'Real-time sentiment analysis and intent recognition' },
          { icon: '📚', title: 'RAG Support', description: 'Connect SOPs, FAQs, and policy documents' },
          { icon: '⚡', title: 'Dynamic Selection', description: 'Each flow chooses optimal provider for its use case' },
        ],
      },
      {
        id: 7,
        type: 'scene',
        title: 'Voice Flows Management',
        content: 'Create and manage multiple voice flows for different use cases  offer acceptance calls in English, Telugu, Kannada, insurance flows, and more. Each flow can be duplicated, edited, and tracked independently.',
        highlight: 'One platform serving dozens of use cases across languages.',
      },
      {
        id: 8,
        type: 'process',
        title: 'CRM Integration Flow',
        content: 'Seamless integration with existing CRM systems for automated trigger and feedback loop.',
        steps: [
          { number: 1, title: 'CRM Trigger', description: 'Offer letter released in CRM triggers API call to voice bot' },
          { number: 2, title: 'AI Initiates Call', description: 'Bot makes outbound call to candidate automatically' },
          { number: 3, title: 'Conversation', description: 'Confirms status, explains next steps, collects feedback' },
          { number: 4, title: 'Data Sync', description: 'Recordings, transcripts, sentiment synced back to CRM' },
        ],
      },
      {
        id: 9,
        type: 'scene',
        title: 'Call Analytics Dashboard',
        content: 'Track every call with detailed metrics including LLM latency, TTS latency, hangup reasons, and call status. Filter by date range and view conversation transcripts with a single click.',
        highlight: 'Complete visibility into AI performance and call outcomes.',
      },
      {
        id: 10,
        type: 'scene',
        title: 'Live Conversation View',
        content: 'Review actual AI conversations with timestamped messages, latency metrics per response, and full transcript history. See exactly how the AI handles different scenarios in real-time.',
        highlight: 'Every conversation becomes actionable intelligence.',
      },
      {
        id: 11,
        type: 'stats',
        title: 'Latency Breakthrough',
        content: 'The hardest and most critical technical win of the project.',
        stats: [
          { value: '2s', label: 'Initial Latency', icon: '🐢' },
          { value: '→', label: 'Optimized To', icon: '⚡' },
          { value: '300ms', label: 'Final Latency', icon: '🚀' },
          { value: '85%', label: 'Reduction', icon: '📉' },
        ],
        highlight: 'Achieved through streaming pipelines, async orchestration, optimized model chaining, and infra-level tuning.',
      },
      {
        id: 12,
        type: 'features',
        title: 'Post-Call Intelligence',
        content: 'After every call, the system automatically processes and extracts valuable insights.',
        features: [
          { icon: '📝', title: 'Transcription', description: 'Full conversation transcripts processed automatically' },
          { icon: '📊', title: 'Structured Feedback', description: 'Extract key data points from conversations' },
          { icon: '😊', title: 'Sentiment Analysis', description: 'Understand candidate/customer emotions' },
          { icon: '🎯', title: 'Intent Tagging', description: 'Categorize call outcomes and intents' },
          { icon: '🎙️', title: 'Recording Storage', description: 'Secure storage of all call recordings' },
          { icon: '🔄', title: 'CRM Sync', description: 'Push insights back to source systems' },
        ],
      },
      {
        id: 13,
        type: 'stats',
        title: 'Business Impact at Natsoft',
        content: 'Real measurable outcomes after deployment.',
        stats: [
          { value: '35-45%', label: 'Reduced Follow-ups', icon: '📉' },
          { value: 'Faster', label: 'Decision Cycles', icon: '⚡' },
          { value: '100%', label: 'Feedback Capture', icon: '📋' },
          { value: 'Scale', label: 'Consistent Experience', icon: '🎯' },
        ],
        highlight: 'Structured visibility into rejection reasons. Recruiters now focus on high-value tasks.',
      },
      {
        id: 14,
        type: 'architecture',
        title: 'Enterprise Features',
        content: 'Built for enterprise governance, security, and multi-tenant operations.',
        layers: [
          { name: 'Multi-Organization Support', description: 'Multiple orgs with isolated data and flows', icon: '🏢', color: '#7C3AED' },
          { name: 'Role-Based Access Control', description: 'Controlled access to flows, analytics, and logs', icon: '🔐', color: '#6D28D9' },
          { name: 'Knowledge Base & RAG', description: 'Connect SOPs and policies for compliant responses', icon: '📚', color: '#5B21B6' },
          { name: 'Audit & Compliance', description: 'Full call recordings and transcript history', icon: '📋', color: '#4C1D95' },
        ],
        highlight: 'Designed for enterprise governance and security from day one.',
      },
      {
        id: 15,
        type: 'conclusion',
        title: 'From Recruitment to Enterprise Platform',
        content: 'What started as a recruitment automation tool evolved into a full enterprise voice platform. Now deployed across recruitment, insurance, sales, and customer support  all from the same configurable platform.',
        highlight: 'One platform. Infinite voice use cases.',
      },
    ],
  },
  {
    id: '10',
    slug: 'setoo-voice-ai',
    title: 'Setoo AI Voice Bot',
    tagline: 'Backend APIs for Enterprise Voice Automation',
    description: 'A backend-only AI voice bot system built for Setoo, later deployed for their enterprise client BU Bhandari and expanded to Vani Connect. Born from a café conversation that turned into an enterprise engagement.',
    role: 'Backend Engineer & AI Developer',
    duration: '3 months',
    year: '2025',
    category: 'ai',
    tech: ['Python', 'FastAPI', 'OpenAI', 'Deepgram', 'ElevenLabs', 'WebSockets', 'PostgreSQL'],
    highlights: [
      'Backend-only architecture for enterprise integration',
      'Deployed for BU Bhandari enterprise client',
      'Sales calls, customer support, and lead engagement',
      'Modular architecture reused across Vani Connect',
      'Born from a café conversation - real inbound opportunity',
    ],
    metrics: [
      { label: 'Deployments', value: '3+' },
      { label: 'Use Cases', value: 'Sales, Support' },
      { label: 'Architecture', value: 'Modular' },
    ],
    images: {
      thumbnail: '/setu-logo.svg',
      coverAspect: '1024/490',
      screenshotFrame: 'dark',
    },
    links: {
      live: 'https://setoo.co/',
    },
    color: '#EF4444',
    featured: true,
    slides: [
      {
        id: 1,
        type: 'intro',
        title: 'The Café Story',
        content: 'This project began inside a café. While working on AI voice integrations, our team discussed STT and TTS pipelines. The Setoo founder overheard, got curious, and asked what we were building.',
        highlight: 'Visibility + real technical depth = inbound opportunity.',
      },
      {
        id: 2,
        type: 'scene',
        title: 'How It Closed',
        content: 'They left for another meeting, then called back while driving, finalized the work, and onboarded us. A genuine technical conversation that became an engagement.',
        highlight: 'From overheard conversation to signed engagement.',
      },
      {
        id: 3,
        type: 'solution',
        title: 'The Project Scope',
        content: 'A backend-only AI voice bot system was built for Setoo, designed to integrate with their existing infrastructure. Later extended for their enterprise client BU Bhandari, and the modular architecture was reused for Vani Connect.',
        highlight: 'Built once, deployed many times across different clients.',
      },
      {
        id: 4,
        type: 'features',
        title: 'Use Cases Delivered',
        content: 'The platform was adapted for multiple voice automation scenarios.',
        features: [
          { icon: '📞', title: 'Sales Calls', description: 'Automated outbound sales conversations with AI' },
          { icon: '🎧', title: 'Customer Support', description: 'AI-powered support call handling and routing' },
          { icon: '🎯', title: 'Lead Engagement', description: 'Automated lead qualification and follow-up calls' },
          { icon: '🔄', title: 'Follow-ups', description: 'Scheduled callback automation' },
          { icon: '📊', title: 'Call Analytics', description: 'Detailed insights from every conversation' },
          { icon: '🔗', title: 'CRM Integration', description: 'Seamless sync with existing systems' },
        ],
      },
      {
        id: 5,
        type: 'architecture',
        title: 'Deployment Architecture',
        content: 'The modular backend architecture enabled rapid deployment across multiple organizations.',
        layers: [
          { name: 'Setoo (Primary)', description: 'Initial deployment and platform development', icon: '🏢', color: '#EF4444' },
          { name: 'BU Bhandari', description: 'Enterprise client deployment via Setoo', icon: '🏗️', color: '#DC2626' },
          { name: 'Vani Connect', description: 'Reused architecture for new client', icon: '📱', color: '#B91C1C' },
        ],
        highlight: 'Same core platform, customized for each client\'s needs.',
      },
      {
        id: 6,
        type: 'stats',
        title: 'Why This Project Matters',
        content: 'A flagship example of how technical depth creates opportunities.',
        stats: [
          { value: '3+', label: 'Organizations', icon: '🏢' },
          { value: 'API', label: 'Backend-Only', icon: '⚙️' },
          { value: 'Modular', label: 'Architecture', icon: '🧩' },
          { value: 'Inbound', label: 'Opportunity', icon: '☕' },
        ],
        highlight: '"We don\'t just call APIs  we build systems."',
      },
      {
        id: 7,
        type: 'conclusion',
        title: 'Lessons Learned',
        content: 'This project is ideal for AI capability showcases, enterprise sales conversations, and technical architecture deep-dives. The café story remains a powerful founder narrative about how visibility and genuine technical expertise create inbound opportunities.',
        highlight: 'Sometimes the best clients find you when you\'re just being yourself.',
      },
    ],
  },
  {
    id: '11',
    slug: 'axion-plan',
    title: 'Axion Plan',
    tagline: 'AI-Powered Financial Forecasting & Business Planning Platform',
    description: 'A B2C financial planning and forecasting platform that helps enterprise leaders model revenues, costs, profitability, and cash flows  converting complex Excel workflows into an intuitive, AI-assisted web platform.',
    role: 'Full Stack Developer & AI Engineer',
    duration: '5 months',
    year: '2025',
    category: 'ai',
    tech: ['React', 'Node.js', 'PostgreSQL', 'OpenAI', 'OCR', 'RAG', 'Stripe'],
    highlights: [
      'Converted proven Excel financial models into scalable SaaS',
      'OCR-based P&L statement ingestion with auto-categorization',
      'AI financial insights with natural language querying',
      'Token-based monetization system',
      'RAG-powered support chatbot',
    ],
    metrics: [
      { label: 'AI Features', value: '3+' },
      { label: 'Industry', value: 'FinTech' },
      { label: 'Audience', value: 'Enterprise' },
    ],
    metricsSection: {
      eyebrow: 'Project Snapshot',
      headline: 'Enterprise financial planning, powered by AI.',
    },
    images: {
      thumbnail: '/axion-logo.png',
      cover: '/axion-work-cover.png',
      coverVideo: '/Axion1.mp4',
      coverAspect: '1024/490',
      screenshotFrame: 'dark',
    },
    links: {
      live: 'https://axionplan.net/',
    },
    color: '#A855F7',
    featured: true,
    slides: [
      {
        id: 1,
        type: 'intro',
        title: 'Project Overview',
        content: 'Axion Plan is a B2C financial planning and forecasting platform designed to help enterprise leaders and decision-makers model revenues, costs, profitability, and cash flows  without relying on complex Excel sheets.',
        highlight: 'Turn proven financial forecasting methodology into a productized, scalable SaaS platform.',
      },
      {
        id: 2,
        type: 'insight',
        title: 'How It Started',
        content: 'The platform was built with a Malaysia-based investment banker and executive coach who works with C-suite leaders. They brought investment banking experience and proven Excel-based financial models.',
        highlight: 'Before Axion Plan, forecasting was done using custom Excel templates  it worked, but it wasn\'t scalable.',
      },
      {
        id: 3,
        type: 'problem',
        title: 'The Problem',
        content: 'Heavy dependence on manual Excel workflows. High learning curve for non-finance users. Difficult to collaborate across teams. No AI-driven insights or explanations. Hard to scale the founder\'s expertise beyond 1:1 engagements.',
        highlight: 'The system worked and clients were paying  but it was trapped in Excel.',
        backgroundVideo: '/Axion2.mp4',
      },
      {
        id: 4,
        type: 'solution',
        title: 'Why This Was Hard',
        content: 'From a tech perspective, this was one of the most challenging projects. The domain was pure finance  P&L statements, balance sheets, cash flow logic, revenue modeling. Coming from a pure tech background required multiple deep-dive sessions, asking critical questions, and reverse-engineering Excel formulas.',
        highlight: 'This project doubled as a hands-on commerce masterclass.',
      },
      {
        id: 17,
        type: 'scene',
        title: 'Sign-In Experience',
        content: 'A focused sign-in screen supports Google OAuth and credential login, with clear access to financial projects and portfolio tools from the first interaction.',
        highlight: 'Secure entry into role-based financial workspaces.',
        image: '/axion-login-framed.png',
        imageAspect: '1024/490',
        imageFrame: 'none',
        imageFit: 'cover',
      },
      {
        id: 18,
        type: 'scene',
        title: 'Portfolio Overview',
        content: 'The portfolio dashboard consolidates revenue, profitability, and operating expenditure across projects, with KPI cards, recent projects, and activity feeds in one executive view.',
        highlight: 'Executive-ready financial summaries without spreadsheet complexity.',
        image: '/axion-portfolio.png',
        imageAspect: '1024/490',
      },
      {
        id: 19,
        type: 'scene',
        title: 'User Profile',
        content: 'Account management covers personal details, role visibility, security settings, and wallet balance, giving owners and team members a single place to manage identity and access.',
        highlight: 'Profile, security, and billing context in one view.',
        image: '/axion-profile.png',
        imageAspect: '1024/490',
      },
      {
        id: 20,
        type: 'scene',
        title: 'Key Performance Indicators',
        content: 'Four metric cards (total projects, YTD revenue, profit before tax, and OPEX) give leaders an at-a-glance read on portfolio health without opening individual models.',
        highlight: 'Headline metrics surfaced where executives need them.',
        image: '/axion-kpi.png',
        imageAspect: '1024/490',
      },
      {
        id: 21,
        type: 'scene',
        title: 'Token Wallet',
        content: 'Usage-based monetization runs through a token wallet. Users see balance, purchase history, and per-action costs for AI insights, projections, and cashflow analysis updates.',
        highlight: 'Transparent token economics aligned with platform value.',
        image: '/axion-wallet-framed.png',
        imageAspect: '1024/490',
        imageFrame: 'none',
        imageFit: 'cover',
      },
      {
        id: 5,
        type: 'architecture',
        title: 'Platform Architecture',
        content: 'Axion Plan was designed as a two-front B2C platform.',
        layers: [
          { name: 'Super Admin Panel', description: 'The operator manages users, monitors usage, and controls settings', icon: '👨‍💼', color: '#A855F7' },
          { name: 'Company Panel', description: 'Organizations create projects, input data, and generate forecasts', icon: '🏢', color: '#9333EA' },
        ],
        highlight: 'Allows Axion Plan to run as a business, not just a tool.',
      },
      {
        id: 6,
        type: 'features',
        title: 'Company Capabilities',
        content: 'Organizations using Axion Plan can manage comprehensive financial planning.',
        features: [
          { icon: '📊', title: 'Revenue Data', description: 'Input and track revenue streams' },
          { icon: '💰', title: 'Cost Structures', description: 'Define direct, indirect, fixed, variable costs' },
          { icon: '📅', title: 'Monthly Distribution', description: 'Break down data by month' },
          { icon: '📈', title: 'Profit Forecasts', description: 'Generate PBT and profitability analysis' },
          { icon: '💵', title: 'Cash Flow Analysis', description: 'Understand cash position over time' },
          { icon: '🎯', title: 'Target Planning', description: 'Model target-based scenarios' },
        ],
      },
      {
        id: 8,
        type: 'features',
        title: 'AI-Powered Enhancements',
        content: 'Features that go beyond what Excel could ever do.',
        backgroundVideo: '/Axion3.mp4',
        features: [
          { icon: '📄', title: 'OCR Data Ingestion', description: 'Upload P&L statements, AI extracts and categorizes costs' },
          { icon: '🤖', title: 'AI Insights', description: 'Ask "Why is profit dropping in month 4?"' },
          { icon: '💬', title: 'Natural Language', description: 'Query financial data in plain English' },
          { icon: '📊', title: 'Context-Aware', description: 'AI uses project-specific data for responses' },
          { icon: '👔', title: 'Executive-Friendly', description: 'Responses in simple, actionable language' },
          { icon: '🔮', title: 'What-If Analysis', description: '"What happens if revenue increases 15%?"' },
        ],
      },
      {
        id: 9,
        type: 'process',
        title: 'Token-Based Monetization',
        content: 'Every feature in Axion Plan works on a token model  usage-based monetization aligned with value delivered.',
        steps: [
          { number: 1, title: 'Wallet System', description: 'Users maintain a token wallet balance' },
          { number: 2, title: 'Token Consumption', description: 'Tokens used for project creation, AI insights, OCR processing' },
          { number: 3, title: 'Top-Up Options', description: 'Users can top-up wallet or subscribe to plans' },
          { number: 4, title: 'Value Alignment', description: 'Pay for what you use, not flat fees' },
        ],
      },
      {
        id: 10,
        type: 'architecture',
        title: 'Role-Based Access',
        content: 'Built for real enterprise collaboration with multiple roles.',
        layers: [
          { name: 'Owner', description: 'Full control over organization and billing', icon: '👑', color: '#A855F7' },
          { name: 'Analyst', description: 'Create and analyze financial models', icon: '📊', color: '#9333EA' },
          { name: 'Editor', description: 'Edit data and update projections', icon: '✏️', color: '#7C3AED' },
          { name: 'Viewer', description: 'Read-only access to reports', icon: '👁️', color: '#6D28D9' },
        ],
        highlight: 'Each role has controlled access to data, insights, and reports.',
      },
      {
        id: 11,
        type: 'solution',
        title: 'RAG-Powered Support',
        content: 'A RAG-powered AI chatbot integrated as the platform\'s support layer. It answers questions about platform usage, financial concepts, and features using internal documentation. If confidence is low, it redirects users to WhatsApp support.',
        highlight: 'Reduces support load while improving user experience.',
      },
      {
        id: 12,
        type: 'stats',
        title: 'Business Impact',
        content: 'Axion Plan enabled transformation of consulting into product.',
        stats: [
          { value: '✓', label: 'Productized Expertise', icon: '📦' },
          { value: 'Fast', label: 'Client Onboarding', icon: '⚡' },
          { value: '-Excel', label: 'Manual Workflows', icon: '📉' },
          { value: 'Scale', label: 'Beyond Consulting', icon: '🚀' },
        ],
        highlight: 'Better understanding of financial data by non-finance leaders.',
      },
      {
        id: 13,
        type: 'conclusion',
        title: 'Why This Project Stands Out',
        content: 'Heavy non-tech domain complexity. Required deep learning outside comfort zone. Accurate translation of financial logic into software. AI used for real augmentation, not gimmicks. Strong alignment between UX, business, and AI.',
        highlight: 'This proves we can build tech for domains we don\'t come from  and still get it right.',
        backgroundVideo: '/Axion4.mp4',
      },
    ],
  },
  {
    id: '12',
    slug: 'course-companion',
    title: 'Course Companion',
    tagline: 'Privacy-First AI Teaching Assistant for Universities & Professors',
    description: 'A privacy-first AI platform built for universities and professors to safely leverage AI in teaching  without compromising data security, intellectual property, or institutional policies. Currently under active development.',
    role: 'Full Stack Developer & AI Engineer',
    duration: 'Ongoing',
    year: '2025',
    category: 'ai',
    tech: ['React', 'Node.js', 'PostgreSQL', 'OpenAI', 'RAG', 'Vector DB'],
    highlights: [
      'Privacy-first by design with minimal data exposure',
      'Professor-controlled AI behavior and content',
      'Zero data lock-in, no model training on student data',
      'Institution-friendly architecture',
      'Three-front platform: Professor, Student, Super Admin',
    ],
    metrics: [
      { label: 'Status', value: 'In Dev' },
      { label: 'Domain', value: 'EdTech' },
      { label: 'Focus', value: 'Privacy' },
    ],
    metricsSection: {
      eyebrow: 'Project Snapshot',
      headline: 'A privacy-first teaching platform in active development.',
    },
    images: {
      thumbnail: '/cc-logo.png',
      cover: '/cc-work-cover.png',
      coverVideo: '/Course.mp4',
      coverAspect: '1024/492',
      screenshotStyle: 'device',
    },
    links: {
      live: 'https://www.coursecompanion.io/',
    },
    color: '#14B8A6',
    featured: true,
    slides: [
      {
        id: 1,
        type: 'intro',
        title: 'Project Overview',
        content: 'Course Companion is a privacy-first AI platform built for universities, professors, and academic institutions to safely leverage AI in teaching  without compromising data security, intellectual property, or institutional policies.',
        highlight: 'A scalable digital extension of a professor with zero data lock-in.',
      },
      {
        id: 2,
        type: 'scene',
        title: 'How It Started',
        content: 'Course Companion was initiated by a technical founder with academic and industry exposure: PhD in Chemistry from Northwestern, AI Fellow at Handshake, based in the United States. Despite working with AI daily, they saw strong resistance to AI adoption in universities.',
        highlight: 'Works closely with cutting-edge AI systems in production environments.',
      },
      {
        id: 3,
        type: 'problem',
        title: 'The Core Problem',
        content: 'Professors are hesitant to use AI tools. Universities often restrict or ban AI platforms. Key concerns include data privacy, student data misuse, intellectual property leakage, and vendor lock-in. Existing AI tools are generic, not professor-centric, and not institution-friendly.',
        highlight: 'Professors don\'t want AI tools. They want a trusted extension of themselves.',
        backgroundVideo: '/Course3.mp4',
      },
      {
        id: 4,
        type: 'solution',
        title: 'Solution Philosophy',
        content: 'Course Companion was designed with privacy and academic trust as first principles. Privacy-first by design. Minimal data exposure. No unnecessary logging. No data reuse for training. Institution-friendly architecture. Professor-controlled AI behavior.',
        highlight: 'The goal is not to replace teaching  but to amplify it safely.',
      },
      {
        id: 5,
        type: 'architecture',
        title: 'Three-Front Architecture',
        content: 'The system is structured into three clearly separated fronts, each with strict responsibility boundaries.',
        layers: [
          { name: 'Professor Front', description: 'Configure and own the AI companion', icon: '👨‍🏫', color: '#14B8A6' },
          { name: 'Student Front', description: 'Chat-based learning interface', icon: '👨‍🎓', color: '#0D9488' },
          { name: 'Super Admin', description: 'Minimal visibility by design', icon: '🔒', color: '#0F766E' },
        ],
        highlight: 'Privacy enforced at every layer.',
      },
      {
        id: 6,
        type: 'features',
        title: 'Professor Capabilities',
        content: 'This is where professors configure and own their AI companion.',
        features: [
          { icon: '📚', title: 'Upload Materials', description: 'Lecture notes, PDFs, reading materials' },
          { icon: '🎨', title: 'Customize AI', description: 'Behavior, response tone, teaching style' },
          { icon: '🏷️', title: 'Personal Branding', description: 'Professor name, course identity' },
          { icon: '🔗', title: 'Shareable Link', description: 'Generate unique course link for students' },
          { icon: '📖', title: 'Content Scope', description: 'Control what AI can and cannot discuss' },
          { icon: '⚙️', title: 'Fine-Tune', description: 'Adjust responses to match teaching philosophy' },
        ],
      },
      {
        id: 17,
        type: 'scene',
        title: 'Sign-In Experience',
        content: 'A focused sign-in flow welcomes professors back with email and password fields, optional extended sessions, and a clear path to account creation, with minimal friction before reaching the teacher portal.',
        highlight: 'Trust starts at the front door with a calm, professional login.',
        image: '/cc-login.png',
      },
      {
        id: 18,
        type: 'scene',
        title: 'Teacher Dashboard',
        content: 'The dashboard surfaces institution branding, course and student counts, AI conversation metrics, and quick actions to create courses, giving professors a single home for their teaching workspace.',
        highlight: 'Institution-aware branding with at-a-glance course health.',
        image: '/cc-dashboard.png',
      },
      {
        id: 19,
        type: 'scene',
        title: 'Course Management',
        content: 'Each course view shows enrollment, chat sessions, uploaded materials, and homework mode controls. Professors configure the AI tutor persona and manage documents that ground student conversations.',
        highlight: 'Professor-owned course spaces with AI tutor configuration built in.',
        image: '/cc-course.png',
      },
      {
        id: 20,
        type: 'scene',
        title: 'Student Roster',
        content: 'The students view tracks enrollments across courses with invite flows and empty states that guide professors to onboard their first class, keeping roster management simple and actionable.',
        highlight: 'Invite and track students without leaving the portal.',
        image: '/cc-students.png',
      },
      {
        id: 21,
        type: 'scene',
        title: 'Institution Branding',
        content: 'Professors upload an institution banner to extract theme colors automatically, preview the active brand, or fall back to a default professional theme, keeping the portal visually aligned with their department.',
        highlight: 'Custom theming without sacrificing a polished default experience.',
        image: '/cc-branding.png',
      },
      {
        id: 7,
        type: 'features',
        title: 'Student Experience',
        content: 'Students interact through a simple, ChatGPT-like UI  intentionally familiar and distraction-free.',
        backgroundVideo: '/Course1.mp4',
        features: [
          { icon: '💬', title: 'Ask Questions', description: 'Directly related to course materials' },
          { icon: '📝', title: 'Clarify Concepts', description: 'Outside classroom hours' },
          { icon: '🔄', title: 'Revise Topics', description: 'At their own pace' },
          { icon: '📊', title: 'Prepare', description: 'For assessments and exams' },
          { icon: '🤝', title: 'Safe Environment', description: 'Non-judgmental interaction' },
          { icon: '👨‍🏫', title: 'Professor\'s Knowledge', description: 'Not generic AI  curated content' },
        ],
      },
      {
        id: 8,
        type: 'process',
        title: 'Privacy Measures',
        content: 'Privacy is not a feature  it is the foundation.',
        steps: [
          { number: 1, title: 'No Logging', description: 'No unnecessary conversation logging' },
          { number: 2, title: 'No Leakage', description: 'No cross-course data leakage' },
          { number: 3, title: 'No Training', description: 'No model training on student data' },
          { number: 4, title: 'Minimal Admin', description: 'Super admin has restricted visibility' },
        ],
      },
      {
        id: 9,
        type: 'stats',
        title: 'Super Admin Boundaries',
        content: 'Unlike traditional platforms, the super admin panel is intentionally restricted. Admins receive only the visibility required to operate the platform, never access to teaching content or private student interactions.',
        stats: [
          { value: '✓', label: 'Professor Count', icon: 'Aggregate platform totals' },
          { value: '✓', label: 'Student Count', icon: 'Enrollment summaries only' },
          { value: '✗', label: 'Conversations', icon: 'Student–AI chats stay private' },
          { value: '✗', label: 'Course Content', icon: 'Uploaded materials remain professor-owned' },
        ],
        highlight: 'Privacy enforced by architecture, not policy promises alone.',
      },
      {
        id: 11,
        type: 'solution',
        title: 'Why This Is Hard',
        content: 'Operates in a high-trust academic environment. Requires balancing AI capability with privacy and institutional compliance. Needs to win over skeptical, highly educated users. Cannot rely on "black-box AI" approaches.',
        highlight: 'This is a harder problem than consumer AI, by design.',
      },
      {
        id: 12,
        type: 'conclusion',
        title: 'Current Status & Vision',
        content: 'Product under active development. Core architecture finalized. Privacy-first design locked. Early-stage builds in progress. Course Companion positions itself at the intersection of AI, Education, Privacy, and Institutional trust.',
        highlight: 'Building AI systems people are comfortable trusting  not just using.',
        backgroundVideo: '/Course2.mp4',
      },
    ],
  },

]
